// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-SNP5qWpGKcCB_ki8JbJMaaP7Ni52L6A',
    appId: '1:859892096227:web:eb815c51c07be380c279d6',
    messagingSenderId: '859892096227',
    projectId: 'savedata-b83dd',
    authDomain: 'savedata-b83dd.firebaseapp.com',
    storageBucket: 'savedata-b83dd.firebasestorage.app',
    measurementId: 'G-5M5E9ERDSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwarUI3OWq167O2mXepGAfD_QdyYDxC1I',
    appId: '1:859892096227:android:9018caf27622794ec279d6',
    messagingSenderId: '859892096227',
    projectId: 'savedata-b83dd',
    storageBucket: 'savedata-b83dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCxR1dD6mqBg1vfVKqS5O5WuFZUgQVHw',
    appId: '1:859892096227:ios:626b324660675cc5c279d6',
    messagingSenderId: '859892096227',
    projectId: 'savedata-b83dd',
    storageBucket: 'savedata-b83dd.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCxR1dD6mqBg1vfVKqS5O5WuFZUgQVHw',
    appId: '1:859892096227:ios:626b324660675cc5c279d6',
    messagingSenderId: '859892096227',
    projectId: 'savedata-b83dd',
    storageBucket: 'savedata-b83dd.firebasestorage.app',
    iosBundleId: 'com.example.fireBaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-SNP5qWpGKcCB_ki8JbJMaaP7Ni52L6A',
    appId: '1:859892096227:web:cb9789d9b5122bbbc279d6',
    messagingSenderId: '859892096227',
    projectId: 'savedata-b83dd',
    authDomain: 'savedata-b83dd.firebaseapp.com',
    storageBucket: 'savedata-b83dd.firebasestorage.app',
    measurementId: 'G-6MT17BC0ME',
  );
}